name: convertor-deploy-aws-ec2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
#  bucket_name: "<example-bucket-name>"
  AWS_REGION: us-east-1

permissions:
  contents: read
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::951515720925:role/Cognito_convertergithubactionsAuth_Role
#          role-session-name: samplerolesession
          aws-region: ${{ env.AWS_REGION }}

      - name: Run linter
        run: echo run linter

      - name: Run tests
        run: echo run xxxxx

      - name: create file
        run: |
          cd ~
          pwd
          touch test
        

