name: converter-deploy-aws-ec2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
#  bucket_name: "<example-bucket-name>"
  AWS_REGION: us-east-1
  REMOTE_HOST: "ec2-54-235-234-66.compute-1.amazonaws.com"
  REMOTE_USER: "ec2-user"
  TARGET: "/home/ec2-user/repos/converter"

permissions:
  contents: read
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::951515720925:role/github-actions-converter
          role-session-name: samplerolesession
          aws-region: ${{ env.AWS_REGION }}
          remote-host: ${{ env.REMOTE_HOST }}
          remote-user: ${{ env.USERNAME }}
      - name: Show user name
        run: echo "$USER"
      - name: create file
        run: |
          pwd
          cd /opt
          mkdir app
        

